#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

void f_run_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[12]*x[0] - y[28] + u[7] + 1; 

}

void g_run_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = p[1]*p[5]*u[0]*y[7] - p[1]*p[5]*u[2]*y[11] - p[1]*y[13]*(p[5]*u[0] - p[5]*u[2]) + 2*p[2]*y[0] - p[2]*y[2] - p[2]*y[4] - p[0]*p[5]*u[0]*y[6] + p[0]*p[5]*u[2]*y[10] + p[0]*y[12]*(p[5]*u[0] - p[5]*u[2]) + 2*p[0]*y[0] - p[0]*y[2] - p[0]*y[4] - y[1]*(2*p[3] + 2*p[1]) - y[3]*(-p[3] - p[1]) - y[5]*(-p[3] - p[1]) - y[22]; 
data[1] = -p[1]*p[5]*u[0]*y[6] + p[1]*p[5]*u[2]*y[10] + p[1]*y[12]*(p[5]*u[0] - p[5]*u[2]) + 2*p[2]*y[1] - p[2]*y[3] - p[2]*y[5] - p[0]*p[5]*u[0]*y[7] + p[0]*p[5]*u[2]*y[11] + p[0]*y[13]*(p[5]*u[0] - p[5]*u[2]) + 2*p[0]*y[1] - p[0]*y[3] - p[0]*y[5] + y[0]*(2*p[3] + 2*p[1]) + y[2]*(-p[3] - p[1]) + y[4]*(-p[3] - p[1]) - y[25]; 
data[2] = -p[1]*p[5]*u[0]*y[7] + p[1]*p[5]*u[1]*y[9] - p[1]*y[13]*(-p[5]*u[0] + p[5]*u[1]) - p[2]*y[0] + 2*p[2]*y[2] - p[2]*y[4] + p[0]*p[5]*u[0]*y[6] - p[0]*p[5]*u[1]*y[8] + p[0]*y[12]*(-p[5]*u[0] + p[5]*u[1]) - p[0]*y[0] + 2*p[0]*y[2] - p[0]*y[4] - y[1]*(-p[3] - p[1]) - y[3]*(2*p[3] + 2*p[1]) - y[5]*(-p[3] - p[1]) - y[23]; 
data[3] = p[1]*p[5]*u[0]*y[6] - p[1]*p[5]*u[1]*y[8] + p[1]*y[12]*(-p[5]*u[0] + p[5]*u[1]) - p[2]*y[1] + 2*p[2]*y[3] - p[2]*y[5] + p[0]*p[5]*u[0]*y[7] - p[0]*p[5]*u[1]*y[9] + p[0]*y[13]*(-p[5]*u[0] + p[5]*u[1]) - p[0]*y[1] + 2*p[0]*y[3] - p[0]*y[5] + y[0]*(-p[3] - p[1]) + y[2]*(2*p[3] + 2*p[1]) + y[4]*(-p[3] - p[1]) - y[26]; 
data[4] = -p[1]*p[5]*u[1]*y[9] + p[1]*p[5]*u[2]*y[11] - p[1]*y[13]*(-p[5]*u[1] + p[5]*u[2]) - p[2]*y[0] - p[2]*y[2] + 2*p[2]*y[4] + p[0]*p[5]*u[1]*y[8] - p[0]*p[5]*u[2]*y[10] + p[0]*y[12]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*y[0] - p[0]*y[2] + 2*p[0]*y[4] - y[1]*(-p[3] - p[1]) - y[3]*(-p[3] - p[1]) - y[5]*(2*p[3] + 2*p[1]) - y[24]; 
data[5] = p[1]*p[5]*u[1]*y[8] - p[1]*p[5]*u[2]*y[10] + p[1]*y[12]*(-p[5]*u[1] + p[5]*u[2]) - p[2]*y[1] - p[2]*y[3] + 2*p[2]*y[5] + p[0]*p[5]*u[1]*y[9] - p[0]*p[5]*u[2]*y[11] + p[0]*y[13]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*y[1] - p[0]*y[3] + 2*p[0]*y[5] + y[0]*(-p[3] - p[1]) + y[2]*(-p[3] - p[1]) + y[4]*(2*p[3] + 2*p[1]) - y[27]; 
data[6] = p[1]*p[5]*u[0]*y[1] - p[1]*p[5]*u[0]*y[3] + p[0]*pow(p[5], 2)*pow(u[0], 2)*y[6] - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[12] - p[0]*p[5]*u[0]*y[0] + p[0]*p[5]*u[0]*y[2] - y[7]*(p[1]*pow(p[5], 2)*pow(u[0], 2) - 8.7735859299284957) + 25.852762655183415*y[6] - 0.9452245073576433*y[9] - 8.9280941624349968*y[8] - 3.4071408952969118*y[11] - 7.4244807333189922*y[10] - y[13]*(-p[1]*pow(p[5], 2)*pow(u[0], 2) + 0.94522450735763719) - 8.9280941624349932*y[12] - 8.7735859299284957*y[15] - 25.852762655183415*y[14] + 0.9452245073576433*y[17] + 8.9280941624349968*y[16] + 3.4071408952969118*y[19] + 7.4244807333189922*y[18] + 0.94522450735763719*y[21] + 8.9280941624349932*y[20]; 
data[7] = -p[1]*p[5]*u[0]*y[0] + p[1]*p[5]*u[0]*y[2] + p[0]*pow(p[5], 2)*pow(u[0], 2)*y[7] - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[13] - p[0]*p[5]*u[0]*y[1] + p[0]*p[5]*u[0]*y[3] + 25.852762655183415*y[7] + y[6]*(p[1]*pow(p[5], 2)*pow(u[0], 2) - 8.7735859299284957) - 8.9280941624349968*y[9] + 0.9452245073576433*y[8] - 7.4244807333189922*y[11] + 3.4071408952969118*y[10] - 8.9280941624349932*y[13] + y[12]*(-p[1]*pow(p[5], 2)*pow(u[0], 2) + 0.94522450735763719) - 25.852762655183415*y[15] + 8.7735859299284957*y[14] + 8.9280941624349968*y[17] - 0.9452245073576433*y[16] + 7.4244807333189922*y[19] - 3.4071408952969118*y[18] + 8.9280941624349932*y[21] - 0.94522450735763719*y[20]; 
data[8] = p[1]*p[5]*u[1]*y[3] - p[1]*p[5]*u[1]*y[5] + p[0]*pow(p[5], 2)*pow(u[1], 2)*y[8] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[12] - p[0]*p[5]*u[1]*y[2] + p[0]*p[5]*u[1]*y[4] - 0.94522450735763885*y[7] - 8.9280941624349914*y[6] - y[9]*(p[1]*pow(p[5], 2)*pow(u[1], 2) - 8.7735859299284975) + 25.852762655183412*y[8] - 0.9452245073576423*y[11] - 8.9280941624349897*y[10] - y[13]*(-p[1]*pow(p[5], 2)*pow(u[1], 2) + 3.4071408952969136) - 7.4244807333189877*y[12] + 0.94522450735763885*y[15] + 8.9280941624349914*y[14] - 8.7735859299284975*y[17] - 25.852762655183412*y[16] + 0.9452245073576423*y[19] + 8.9280941624349897*y[18] + 3.4071408952969136*y[21] + 7.4244807333189877*y[20]; 
data[9] = -p[1]*p[5]*u[1]*y[2] + p[1]*p[5]*u[1]*y[4] + p[0]*pow(p[5], 2)*pow(u[1], 2)*y[9] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[13] - p[0]*p[5]*u[1]*y[3] + p[0]*p[5]*u[1]*y[5] - 8.9280941624349914*y[7] + 0.94522450735763885*y[6] + 25.852762655183412*y[9] + y[8]*(p[1]*pow(p[5], 2)*pow(u[1], 2) - 8.7735859299284975) - 8.9280941624349897*y[11] + 0.9452245073576423*y[10] - 7.4244807333189877*y[13] + y[12]*(-p[1]*pow(p[5], 2)*pow(u[1], 2) + 3.4071408952969136) + 8.9280941624349914*y[15] - 0.94522450735763885*y[14] - 25.852762655183412*y[17] + 8.7735859299284975*y[16] + 8.9280941624349897*y[19] - 0.9452245073576423*y[18] + 7.4244807333189877*y[21] - 3.4071408952969136*y[20]; 
data[10] = -p[1]*p[5]*u[2]*y[1] + p[1]*p[5]*u[2]*y[5] + p[0]*pow(p[5], 2)*pow(u[2], 2)*y[10] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[12] + p[0]*p[5]*u[2]*y[0] - p[0]*p[5]*u[2]*y[4] - 3.4071408952969162*y[7] - 7.4244807333189904*y[6] - 0.94522450735764241*y[9] - 8.9280941624349932*y[8] - y[11]*(p[1]*pow(p[5], 2)*pow(u[2], 2) - 8.7735859299285011) + 25.852762655183412*y[10] - y[13]*(-p[1]*pow(p[5], 2)*pow(u[2], 2) + 0.94522450735763919) - 8.928094162434995*y[12] + 3.4071408952969162*y[15] + 7.4244807333189904*y[14] + 0.94522450735764241*y[17] + 8.9280941624349932*y[16] - 8.7735859299285011*y[19] - 25.852762655183412*y[18] + 0.94522450735763919*y[21] + 8.928094162434995*y[20]; 
data[11] = p[1]*p[5]*u[2]*y[0] - p[1]*p[5]*u[2]*y[4] + p[0]*pow(p[5], 2)*pow(u[2], 2)*y[11] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[13] + p[0]*p[5]*u[2]*y[1] - p[0]*p[5]*u[2]*y[5] - 7.4244807333189904*y[7] + 3.4071408952969162*y[6] - 8.9280941624349932*y[9] + 0.94522450735764241*y[8] + 25.852762655183412*y[11] + y[10]*(p[1]*pow(p[5], 2)*pow(u[2], 2) - 8.7735859299285011) - 8.928094162434995*y[13] + y[12]*(-p[1]*pow(p[5], 2)*pow(u[2], 2) + 0.94522450735763919) + 7.4244807333189904*y[15] - 3.4071408952969162*y[14] + 8.9280941624349932*y[17] - 0.94522450735764241*y[16] - 25.852762655183412*y[19] + 8.7735859299285011*y[18] + 8.928094162434995*y[21] - 0.94522450735763919*y[20]; 
data[12] = -p[1]*y[1]*(p[5]*u[0] - p[5]*u[2]) - p[1]*y[3]*(-p[5]*u[0] + p[5]*u[1]) - p[1]*y[5]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[6] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[8] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[10] + p[0]*y[0]*(p[5]*u[0] - p[5]*u[2]) + p[0]*y[2]*(-p[5]*u[0] + p[5]*u[1]) + p[0]*y[4]*(-p[5]*u[1] + p[5]*u[2]) - y[7]*(-p[1]*pow(p[5], 2)*pow(u[0], 2) + 0.94522450735763774) - 8.9280941624349932*y[6] - y[9]*(-p[1]*pow(p[5], 2)*pow(u[1], 2) + 3.4071408952969091) - 7.4244807333189868*y[8] - y[11]*(-p[1]*pow(p[5], 2)*pow(u[2], 2) + 0.94522450735764263) - 8.9280941624349932*y[10] - y[13]*(p[1]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + p[7] - 8.7735859299284922) + y[12]*p[6] + 25.852762655183412*y[12] + 0.94522450735763774*y[15] + 8.9280941624349932*y[14] + 3.4071408952969091*y[17] + 7.4244807333189868*y[16] + 0.94522450735764263*y[19] + 8.9280941624349932*y[18] - 8.7735859299284922*y[21] - 25.852762655183412*y[20] + y[12]*(p[0]*p[4]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + 1)/p[4]; 
data[13] = p[1]*y[0]*(p[5]*u[0] - p[5]*u[2]) + p[1]*y[2]*(-p[5]*u[0] + p[5]*u[1]) + p[1]*y[4]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[7] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[9] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[11] + p[0]*y[1]*(p[5]*u[0] - p[5]*u[2]) + p[0]*y[3]*(-p[5]*u[0] + p[5]*u[1]) + p[0]*y[5]*(-p[5]*u[1] + p[5]*u[2]) - 8.9280941624349932*y[7] + y[6]*(-p[1]*pow(p[5], 2)*pow(u[0], 2) + 0.94522450735763774) - 7.4244807333189868*y[9] + y[8]*(-p[1]*pow(p[5], 2)*pow(u[1], 2) + 3.4071408952969091) - 8.9280941624349932*y[11] + y[10]*(-p[1]*pow(p[5], 2)*pow(u[2], 2) + 0.94522450735764263) + y[13]*p[6] + 25.852762655183412*y[13] + y[12]*(p[1]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + p[7] - 8.7735859299284922) + 8.9280941624349932*y[15] - 0.94522450735763774*y[14] + 7.4244807333189868*y[17] - 3.4071408952969091*y[16] + 8.9280941624349932*y[19] - 0.94522450735764263*y[18] - 25.852762655183412*y[21] + 8.7735859299284922*y[20] + y[13]*(p[0]*p[4]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + 1)/p[4]; 
data[14] = -8.7735859299284957*y[7] - 25.852762655183415*y[6] + 0.9452245073576433*y[9] + 8.9280941624349968*y[8] + 3.4071408952969118*y[11] + 7.4244807333189922*y[10] + 0.94522450735763719*y[13] + 8.9280941624349932*y[12] + 8.7735859299284957*y[15] + 25.852762655183415*y[14] - 0.9452245073576433*y[17] - 8.9280941624349968*y[16] - 3.4071408952969118*y[19] - 7.4244807333189922*y[18] - 0.94522450735763719*y[21] - 8.9280941624349932*y[20]; 
data[15] = -25.852762655183415*y[7] + 8.7735859299284957*y[6] + 8.9280941624349968*y[9] - 0.9452245073576433*y[8] + 7.4244807333189922*y[11] - 3.4071408952969118*y[10] + 8.9280941624349932*y[13] - 0.94522450735763719*y[12] + 25.852762655183415*y[15] - 8.7735859299284957*y[14] - 8.9280941624349968*y[17] + 0.9452245073576433*y[16] - 7.4244807333189922*y[19] + 3.4071408952969118*y[18] - 8.9280941624349932*y[21] + 0.94522450735763719*y[20]; 
data[16] = 0.94522450735763885*y[7] + 8.9280941624349914*y[6] - 8.7735859299284975*y[9] - 25.852762655183412*y[8] + 0.9452245073576423*y[11] + 8.9280941624349897*y[10] + 3.4071408952969136*y[13] + 7.4244807333189877*y[12] - 0.94522450735763885*y[15] - 8.9280941624349914*y[14] + 8.7735859299284975*y[17] + 25.852762655183412*y[16] - 0.9452245073576423*y[19] - 8.9280941624349897*y[18] - 3.4071408952969136*y[21] - 7.4244807333189877*y[20]; 
data[17] = 8.9280941624349914*y[7] - 0.94522450735763885*y[6] - 25.852762655183412*y[9] + 8.7735859299284975*y[8] + 8.9280941624349897*y[11] - 0.9452245073576423*y[10] + 7.4244807333189877*y[13] - 3.4071408952969136*y[12] - 8.9280941624349914*y[15] + 0.94522450735763885*y[14] + 25.852762655183412*y[17] - 8.7735859299284975*y[16] - 8.9280941624349897*y[19] + 0.9452245073576423*y[18] - 7.4244807333189877*y[21] + 3.4071408952969136*y[20]; 
data[18] = 3.4071408952969162*y[7] + 7.4244807333189904*y[6] + 0.94522450735764241*y[9] + 8.9280941624349932*y[8] - 8.7735859299285011*y[11] - 25.852762655183412*y[10] + 0.94522450735763919*y[13] + 8.928094162434995*y[12] - 3.4071408952969162*y[15] - 7.4244807333189904*y[14] - 0.94522450735764241*y[17] - 8.9280941624349932*y[16] + 8.7735859299285011*y[19] + 25.852762655183412*y[18] - 0.94522450735763919*y[21] - 8.928094162434995*y[20]; 
data[19] = 7.4244807333189904*y[7] - 3.4071408952969162*y[6] + 8.9280941624349932*y[9] - 0.94522450735764241*y[8] - 25.852762655183412*y[11] + 8.7735859299285011*y[10] + 8.928094162434995*y[13] - 0.94522450735763919*y[12] - 7.4244807333189904*y[15] + 3.4071408952969162*y[14] - 8.9280941624349932*y[17] + 0.94522450735764241*y[16] + 25.852762655183412*y[19] - 8.7735859299285011*y[18] - 8.928094162434995*y[21] + 0.94522450735763919*y[20]; 
data[20] = 0.94522450735763774*y[7] + 8.9280941624349932*y[6] + 3.4071408952969091*y[9] + 7.4244807333189868*y[8] + 0.94522450735764263*y[11] + 8.9280941624349932*y[10] - 8.7735859299284922*y[13] - 25.852762655183412*y[12] - 0.94522450735763774*y[15] - 8.9280941624349932*y[14] - 3.4071408952969091*y[17] - 7.4244807333189868*y[16] - 0.94522450735764263*y[19] - 8.9280941624349932*y[18] + 8.7735859299284922*y[21] + 25.852762655183412*y[20]; 
data[21] = 8.9280941624349932*y[7] - 0.94522450735763774*y[6] + 7.4244807333189868*y[9] - 3.4071408952969091*y[8] + 8.9280941624349932*y[11] - 0.94522450735764263*y[10] - 25.852762655183412*y[13] + 8.7735859299284922*y[12] - 8.9280941624349932*y[15] + 0.94522450735763774*y[14] - 7.4244807333189868*y[17] + 3.4071408952969091*y[16] - 8.9280941624349932*y[19] + 0.94522450735764263*y[18] + 25.852762655183412*y[21] - 8.7735859299284922*y[20]; 
data[22] = -p[9]*y[22] - y[0] + 1.0*p[8]*y[25] + u[3]*cos(u[6]); 
data[23] = -p[9]*y[23] - y[2] + 1.0*p[8]*y[26] + u[4]*cos(u[6] - 2.0943951023931953); 
data[24] = -p[9]*y[24] - y[4] + 1.0*p[8]*y[27] + u[5]*cos(u[6] - 4.1887902047863905); 
data[25] = -1.0*p[9]*y[25] - 1.0*y[1] - 1.0*p[8]*y[22] + 1.0*u[3]*sin(u[6]); 
data[26] = -1.0*p[9]*y[26] - 1.0*y[3] - 1.0*p[8]*y[23] + 1.0*u[4]*sin(u[6] - 2.0943951023931953); 
data[27] = -1.0*p[9]*y[27] - 1.0*y[5] - 1.0*p[8]*y[24] + 1.0*u[5]*sin(u[6] - 4.1887902047863905); 
data[28] = 1.0 - y[28]; 
data[29] = p[11]*x[0] + p[10]*(1 - y[28]) - y[29]; 

}

void h_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = 8.7735859299284957*y[7] + 25.852762655183415*y[6] - 0.9452245073576433*y[9] - 8.9280941624349968*y[8] - 3.4071408952969118*y[11] - 7.4244807333189922*y[10] - 0.94522450735763719*y[13] - 8.9280941624349932*y[12] - 8.7735859299284957*y[15] - 25.852762655183415*y[14] + 0.9452245073576433*y[17] + 8.9280941624349968*y[16] + 3.4071408952969118*y[19] + 7.4244807333189922*y[18] + 0.94522450735763719*y[21] + 8.9280941624349932*y[20]; 
data[1] = 25.852762655183415*y[7] - 8.7735859299284957*y[6] - 8.9280941624349968*y[9] + 0.9452245073576433*y[8] - 7.4244807333189922*y[11] + 3.4071408952969118*y[10] - 8.9280941624349932*y[13] + 0.94522450735763719*y[12] - 25.852762655183415*y[15] + 8.7735859299284957*y[14] + 8.9280941624349968*y[17] - 0.9452245073576433*y[16] + 7.4244807333189922*y[19] - 3.4071408952969118*y[18] + 8.9280941624349932*y[21] - 0.94522450735763719*y[20]; 
data[2] = -0.94522450735763885*y[7] - 8.9280941624349914*y[6] + 8.7735859299284975*y[9] + 25.852762655183412*y[8] - 0.9452245073576423*y[11] - 8.9280941624349897*y[10] - 3.4071408952969136*y[13] - 7.4244807333189877*y[12] + 0.94522450735763885*y[15] + 8.9280941624349914*y[14] - 8.7735859299284975*y[17] - 25.852762655183412*y[16] + 0.9452245073576423*y[19] + 8.9280941624349897*y[18] + 3.4071408952969136*y[21] + 7.4244807333189877*y[20]; 
data[3] = -8.9280941624349914*y[7] + 0.94522450735763885*y[6] + 25.852762655183412*y[9] - 8.7735859299284975*y[8] - 8.9280941624349897*y[11] + 0.9452245073576423*y[10] - 7.4244807333189877*y[13] + 3.4071408952969136*y[12] + 8.9280941624349914*y[15] - 0.94522450735763885*y[14] - 25.852762655183412*y[17] + 8.7735859299284975*y[16] + 8.9280941624349897*y[19] - 0.9452245073576423*y[18] + 7.4244807333189877*y[21] - 3.4071408952969136*y[20]; 
data[4] = -3.4071408952969162*y[7] - 7.4244807333189904*y[6] - 0.94522450735764241*y[9] - 8.9280941624349932*y[8] + 8.7735859299285011*y[11] + 25.852762655183412*y[10] - 0.94522450735763919*y[13] - 8.928094162434995*y[12] + 3.4071408952969162*y[15] + 7.4244807333189904*y[14] + 0.94522450735764241*y[17] + 8.9280941624349932*y[16] - 8.7735859299285011*y[19] - 25.852762655183412*y[18] + 0.94522450735763919*y[21] + 8.928094162434995*y[20]; 
data[5] = -7.4244807333189904*y[7] + 3.4071408952969162*y[6] - 8.9280941624349932*y[9] + 0.94522450735764241*y[8] + 25.852762655183412*y[11] - 8.7735859299285011*y[10] - 8.928094162434995*y[13] + 0.94522450735763919*y[12] + 7.4244807333189904*y[15] - 3.4071408952969162*y[14] + 8.9280941624349932*y[17] - 0.94522450735764241*y[16] - 25.852762655183412*y[19] + 8.7735859299285011*y[18] + 8.928094162434995*y[21] - 0.94522450735763919*y[20]; 
data[6] = -0.94522450735763774*y[7] - 8.9280941624349932*y[6] - 3.4071408952969091*y[9] - 7.4244807333189868*y[8] - 0.94522450735764263*y[11] - 8.9280941624349932*y[10] + 8.7735859299284922*y[13] + 25.852762655183412*y[12] + 0.94522450735763774*y[15] + 8.9280941624349932*y[14] + 3.4071408952969091*y[17] + 7.4244807333189868*y[16] + 0.94522450735764263*y[19] + 8.9280941624349932*y[18] - 8.7735859299284922*y[21] - 25.852762655183412*y[20]; 
data[7] = -8.9280941624349932*y[7] + 0.94522450735763774*y[6] - 7.4244807333189868*y[9] + 3.4071408952969091*y[8] - 8.9280941624349932*y[11] + 0.94522450735764263*y[10] + 25.852762655183412*y[13] - 8.7735859299284922*y[12] + 8.9280941624349932*y[15] - 0.94522450735763774*y[14] + 7.4244807333189868*y[17] - 3.4071408952969091*y[16] + 8.9280941624349932*y[19] - 0.94522450735764263*y[18] - 25.852762655183412*y[21] + 8.7735859299284922*y[20]; 
data[8] = p[1]*p[5]*u[0]*y[7] - p[1]*p[5]*u[2]*y[11] - p[1]*y[13]*(p[5]*u[0] - p[5]*u[2]) + 2*p[2]*y[0] - p[2]*y[2] - p[2]*y[4] - p[0]*p[5]*u[0]*y[6] + p[0]*p[5]*u[2]*y[10] + p[0]*y[12]*(p[5]*u[0] - p[5]*u[2]) + 2*p[0]*y[0] - p[0]*y[2] - p[0]*y[4] - y[1]*(2*p[3] + 2*p[1]) - y[3]*(-p[3] - p[1]) - y[5]*(-p[3] - p[1]); 
data[9] = -p[1]*p[5]*u[0]*y[6] + p[1]*p[5]*u[2]*y[10] + p[1]*y[12]*(p[5]*u[0] - p[5]*u[2]) + 2*p[2]*y[1] - p[2]*y[3] - p[2]*y[5] - p[0]*p[5]*u[0]*y[7] + p[0]*p[5]*u[2]*y[11] + p[0]*y[13]*(p[5]*u[0] - p[5]*u[2]) + 2*p[0]*y[1] - p[0]*y[3] - p[0]*y[5] + y[0]*(2*p[3] + 2*p[1]) + y[2]*(-p[3] - p[1]) + y[4]*(-p[3] - p[1]); 
data[10] = -p[1]*p[5]*u[0]*y[7] + p[1]*p[5]*u[1]*y[9] - p[1]*y[13]*(-p[5]*u[0] + p[5]*u[1]) - p[2]*y[0] + 2*p[2]*y[2] - p[2]*y[4] + p[0]*p[5]*u[0]*y[6] - p[0]*p[5]*u[1]*y[8] + p[0]*y[12]*(-p[5]*u[0] + p[5]*u[1]) - p[0]*y[0] + 2*p[0]*y[2] - p[0]*y[4] - y[1]*(-p[3] - p[1]) - y[3]*(2*p[3] + 2*p[1]) - y[5]*(-p[3] - p[1]); 
data[11] = p[1]*p[5]*u[0]*y[6] - p[1]*p[5]*u[1]*y[8] + p[1]*y[12]*(-p[5]*u[0] + p[5]*u[1]) - p[2]*y[1] + 2*p[2]*y[3] - p[2]*y[5] + p[0]*p[5]*u[0]*y[7] - p[0]*p[5]*u[1]*y[9] + p[0]*y[13]*(-p[5]*u[0] + p[5]*u[1]) - p[0]*y[1] + 2*p[0]*y[3] - p[0]*y[5] + y[0]*(-p[3] - p[1]) + y[2]*(2*p[3] + 2*p[1]) + y[4]*(-p[3] - p[1]); 
data[12] = -p[1]*p[5]*u[1]*y[9] + p[1]*p[5]*u[2]*y[11] - p[1]*y[13]*(-p[5]*u[1] + p[5]*u[2]) - p[2]*y[0] - p[2]*y[2] + 2*p[2]*y[4] + p[0]*p[5]*u[1]*y[8] - p[0]*p[5]*u[2]*y[10] + p[0]*y[12]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*y[0] - p[0]*y[2] + 2*p[0]*y[4] - y[1]*(-p[3] - p[1]) - y[3]*(-p[3] - p[1]) - y[5]*(2*p[3] + 2*p[1]); 
data[13] = p[1]*p[5]*u[1]*y[8] - p[1]*p[5]*u[2]*y[10] + p[1]*y[12]*(-p[5]*u[1] + p[5]*u[2]) - p[2]*y[1] - p[2]*y[3] + 2*p[2]*y[5] + p[0]*p[5]*u[1]*y[9] - p[0]*p[5]*u[2]*y[11] + p[0]*y[13]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*y[1] - p[0]*y[3] + 2*p[0]*y[5] + y[0]*(-p[3] - p[1]) + y[2]*(-p[3] - p[1]) + y[4]*(2*p[3] + 2*p[1]); 
data[14] = -p[1]*pow(p[5], 2)*pow(u[0], 2)*y[7] + p[1]*pow(p[5], 2)*pow(u[0], 2)*y[13] + p[1]*p[5]*u[0]*y[1] - p[1]*p[5]*u[0]*y[3] + p[0]*pow(p[5], 2)*pow(u[0], 2)*y[6] - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[12] - p[0]*p[5]*u[0]*y[0] + p[0]*p[5]*u[0]*y[2]; 
data[15] = p[1]*pow(p[5], 2)*pow(u[0], 2)*y[6] - p[1]*pow(p[5], 2)*pow(u[0], 2)*y[12] - p[1]*p[5]*u[0]*y[0] + p[1]*p[5]*u[0]*y[2] + p[0]*pow(p[5], 2)*pow(u[0], 2)*y[7] - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[13] - p[0]*p[5]*u[0]*y[1] + p[0]*p[5]*u[0]*y[3]; 
data[16] = -p[1]*pow(p[5], 2)*pow(u[1], 2)*y[9] + p[1]*pow(p[5], 2)*pow(u[1], 2)*y[13] + p[1]*p[5]*u[1]*y[3] - p[1]*p[5]*u[1]*y[5] + p[0]*pow(p[5], 2)*pow(u[1], 2)*y[8] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[12] - p[0]*p[5]*u[1]*y[2] + p[0]*p[5]*u[1]*y[4]; 
data[17] = p[1]*pow(p[5], 2)*pow(u[1], 2)*y[8] - p[1]*pow(p[5], 2)*pow(u[1], 2)*y[12] - p[1]*p[5]*u[1]*y[2] + p[1]*p[5]*u[1]*y[4] + p[0]*pow(p[5], 2)*pow(u[1], 2)*y[9] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[13] - p[0]*p[5]*u[1]*y[3] + p[0]*p[5]*u[1]*y[5]; 
data[18] = -p[1]*pow(p[5], 2)*pow(u[2], 2)*y[11] + p[1]*pow(p[5], 2)*pow(u[2], 2)*y[13] - p[1]*p[5]*u[2]*y[1] + p[1]*p[5]*u[2]*y[5] + p[0]*pow(p[5], 2)*pow(u[2], 2)*y[10] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[12] + p[0]*p[5]*u[2]*y[0] - p[0]*p[5]*u[2]*y[4]; 
data[19] = p[1]*pow(p[5], 2)*pow(u[2], 2)*y[10] - p[1]*pow(p[5], 2)*pow(u[2], 2)*y[12] + p[1]*p[5]*u[2]*y[0] - p[1]*p[5]*u[2]*y[4] + p[0]*pow(p[5], 2)*pow(u[2], 2)*y[11] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[13] + p[0]*p[5]*u[2]*y[1] - p[0]*p[5]*u[2]*y[5]; 
data[20] = p[1]*pow(p[5], 2)*pow(u[0], 2)*y[7] + p[1]*pow(p[5], 2)*pow(u[1], 2)*y[9] + p[1]*pow(p[5], 2)*pow(u[2], 2)*y[11] - p[1]*y[13]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) - p[1]*y[1]*(p[5]*u[0] - p[5]*u[2]) - p[1]*y[3]*(-p[5]*u[0] + p[5]*u[1]) - p[1]*y[5]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[6] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[8] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[10] + p[0]*y[0]*(p[5]*u[0] - p[5]*u[2]) + p[0]*y[2]*(-p[5]*u[0] + p[5]*u[1]) + p[0]*y[4]*(-p[5]*u[1] + p[5]*u[2]) + y[12]*(p[0]*p[4]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + 1)/p[4]; 
data[21] = -p[1]*pow(p[5], 2)*pow(u[0], 2)*y[6] - p[1]*pow(p[5], 2)*pow(u[1], 2)*y[8] - p[1]*pow(p[5], 2)*pow(u[2], 2)*y[10] + p[1]*y[12]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + p[1]*y[0]*(p[5]*u[0] - p[5]*u[2]) + p[1]*y[2]*(-p[5]*u[0] + p[5]*u[1]) + p[1]*y[4]*(-p[5]*u[1] + p[5]*u[2]) - p[0]*pow(p[5], 2)*pow(u[0], 2)*y[7] - p[0]*pow(p[5], 2)*pow(u[1], 2)*y[9] - p[0]*pow(p[5], 2)*pow(u[2], 2)*y[11] + p[0]*y[1]*(p[5]*u[0] - p[5]*u[2]) + p[0]*y[3]*(-p[5]*u[0] + p[5]*u[1]) + p[0]*y[5]*(-p[5]*u[1] + p[5]*u[2]) + y[13]*(p[0]*p[4]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + 1)/p[4]; 
data[22] = sqrt(1.0*pow(y[25], 2) + pow(y[22], 2)); 
data[23] = sqrt(1.0*pow(y[26], 2) + pow(y[23], 2)); 
data[24] = sqrt(1.0*pow(y[27], 2) + pow(y[24], 2)); 
data[25] = 1.0*y[1]*y[25] + y[0]*y[22] + 1.0*y[3]*y[26] + y[2]*y[23] + 1.0*y[5]*y[27] + y[4]*y[24]; 
data[26] = 1.0*y[1]*y[22] - 1.0*y[0]*y[25] + 1.0*y[3]*y[23] - 1.0*y[2]*y[26] + 1.0*y[5]*y[24] - 1.0*y[4]*y[27]; 
data[27] = x[0]; 
data[28] = u[7]; 

}

void de_jac_run_up_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[0] = -p[12]; 
data[32] = 2*p[2] + 2*p[0]; 
data[33] = -2*p[3] - 2*p[1]; 
data[34] = -p[2] - p[0]; 
data[35] = p[3] + p[1]; 
data[36] = -p[2] - p[0]; 
data[37] = p[3] + p[1]; 
data[38] = -p[0]*p[5]*u[0]; 
data[39] = p[1]*p[5]*u[0]; 
data[42] = p[0]*p[5]*u[2]; 
data[43] = -p[1]*p[5]*u[2]; 
data[44] = p[0]*(p[5]*u[0] - p[5]*u[2]); 
data[45] = -p[1]*(p[5]*u[0] - p[5]*u[2]); 
data[63] = 2*p[3] + 2*p[1]; 
data[64] = 2*p[2] + 2*p[0]; 
data[65] = -p[3] - p[1]; 
data[66] = -p[2] - p[0]; 
data[67] = -p[3] - p[1]; 
data[68] = -p[2] - p[0]; 
data[69] = -p[1]*p[5]*u[0]; 
data[70] = -p[0]*p[5]*u[0]; 
data[73] = p[1]*p[5]*u[2]; 
data[74] = p[0]*p[5]*u[2]; 
data[75] = p[1]*(p[5]*u[0] - p[5]*u[2]); 
data[76] = p[0]*(p[5]*u[0] - p[5]*u[2]); 
data[94] = -p[2] - p[0]; 
data[95] = p[3] + p[1]; 
data[96] = 2*p[2] + 2*p[0]; 
data[97] = -2*p[3] - 2*p[1]; 
data[98] = -p[2] - p[0]; 
data[99] = p[3] + p[1]; 
data[100] = p[0]*p[5]*u[0]; 
data[101] = -p[1]*p[5]*u[0]; 
data[102] = -p[0]*p[5]*u[1]; 
data[103] = p[1]*p[5]*u[1]; 
data[106] = p[0]*(-p[5]*u[0] + p[5]*u[1]); 
data[107] = -p[1]*(-p[5]*u[0] + p[5]*u[1]); 
data[125] = -p[3] - p[1]; 
data[126] = -p[2] - p[0]; 
data[127] = 2*p[3] + 2*p[1]; 
data[128] = 2*p[2] + 2*p[0]; 
data[129] = -p[3] - p[1]; 
data[130] = -p[2] - p[0]; 
data[131] = p[1]*p[5]*u[0]; 
data[132] = p[0]*p[5]*u[0]; 
data[133] = -p[1]*p[5]*u[1]; 
data[134] = -p[0]*p[5]*u[1]; 
data[137] = p[1]*(-p[5]*u[0] + p[5]*u[1]); 
data[138] = p[0]*(-p[5]*u[0] + p[5]*u[1]); 
data[156] = -p[2] - p[0]; 
data[157] = p[3] + p[1]; 
data[158] = -p[2] - p[0]; 
data[159] = p[3] + p[1]; 
data[160] = 2*p[2] + 2*p[0]; 
data[161] = -2*p[3] - 2*p[1]; 
data[164] = p[0]*p[5]*u[1]; 
data[165] = -p[1]*p[5]*u[1]; 
data[166] = -p[0]*p[5]*u[2]; 
data[167] = p[1]*p[5]*u[2]; 
data[168] = p[0]*(-p[5]*u[1] + p[5]*u[2]); 
data[169] = -p[1]*(-p[5]*u[1] + p[5]*u[2]); 
data[187] = -p[3] - p[1]; 
data[188] = -p[2] - p[0]; 
data[189] = -p[3] - p[1]; 
data[190] = -p[2] - p[0]; 
data[191] = 2*p[3] + 2*p[1]; 
data[192] = 2*p[2] + 2*p[0]; 
data[195] = p[1]*p[5]*u[1]; 
data[196] = p[0]*p[5]*u[1]; 
data[197] = -p[1]*p[5]*u[2]; 
data[198] = -p[0]*p[5]*u[2]; 
data[199] = p[1]*(-p[5]*u[1] + p[5]*u[2]); 
data[200] = p[0]*(-p[5]*u[1] + p[5]*u[2]); 
data[218] = -p[0]*p[5]*u[0]; 
data[219] = p[1]*p[5]*u[0]; 
data[220] = p[0]*p[5]*u[0]; 
data[221] = -p[1]*p[5]*u[0]; 
data[224] = p[0]*pow(p[5], 2)*pow(u[0], 2) + 25.852762655183415; 
data[225] = -p[1]*pow(p[5], 2)*pow(u[0], 2) + 8.7735859299284957; 
data[230] = -p[0]*pow(p[5], 2)*pow(u[0], 2) - 8.9280941624349932; 
data[231] = p[1]*pow(p[5], 2)*pow(u[0], 2) - 0.94522450735763719; 
data[249] = -p[1]*p[5]*u[0]; 
data[250] = -p[0]*p[5]*u[0]; 
data[251] = p[1]*p[5]*u[0]; 
data[252] = p[0]*p[5]*u[0]; 
data[255] = p[1]*pow(p[5], 2)*pow(u[0], 2) - 8.7735859299284957; 
data[256] = p[0]*pow(p[5], 2)*pow(u[0], 2) + 25.852762655183415; 
data[261] = -p[1]*pow(p[5], 2)*pow(u[0], 2) + 0.94522450735763719; 
data[262] = -p[0]*pow(p[5], 2)*pow(u[0], 2) - 8.9280941624349932; 
data[282] = -p[0]*p[5]*u[1]; 
data[283] = p[1]*p[5]*u[1]; 
data[284] = p[0]*p[5]*u[1]; 
data[285] = -p[1]*p[5]*u[1]; 
data[288] = p[0]*pow(p[5], 2)*pow(u[1], 2) + 25.852762655183412; 
data[289] = -p[1]*pow(p[5], 2)*pow(u[1], 2) + 8.7735859299284975; 
data[292] = -p[0]*pow(p[5], 2)*pow(u[1], 2) - 7.4244807333189877; 
data[293] = p[1]*pow(p[5], 2)*pow(u[1], 2) - 3.4071408952969136; 
data[313] = -p[1]*p[5]*u[1]; 
data[314] = -p[0]*p[5]*u[1]; 
data[315] = p[1]*p[5]*u[1]; 
data[316] = p[0]*p[5]*u[1]; 
data[319] = p[1]*pow(p[5], 2)*pow(u[1], 2) - 8.7735859299284975; 
data[320] = p[0]*pow(p[5], 2)*pow(u[1], 2) + 25.852762655183412; 
data[323] = -p[1]*pow(p[5], 2)*pow(u[1], 2) + 3.4071408952969136; 
data[324] = -p[0]*pow(p[5], 2)*pow(u[1], 2) - 7.4244807333189877; 
data[342] = p[0]*p[5]*u[2]; 
data[343] = -p[1]*p[5]*u[2]; 
data[346] = -p[0]*p[5]*u[2]; 
data[347] = p[1]*p[5]*u[2]; 
data[352] = p[0]*pow(p[5], 2)*pow(u[2], 2) + 25.852762655183412; 
data[353] = -p[1]*pow(p[5], 2)*pow(u[2], 2) + 8.7735859299285011; 
data[354] = -p[0]*pow(p[5], 2)*pow(u[2], 2) - 8.928094162434995; 
data[355] = p[1]*pow(p[5], 2)*pow(u[2], 2) - 0.94522450735763919; 
data[373] = p[1]*p[5]*u[2]; 
data[374] = p[0]*p[5]*u[2]; 
data[377] = -p[1]*p[5]*u[2]; 
data[378] = -p[0]*p[5]*u[2]; 
data[383] = p[1]*pow(p[5], 2)*pow(u[2], 2) - 8.7735859299285011; 
data[384] = p[0]*pow(p[5], 2)*pow(u[2], 2) + 25.852762655183412; 
data[385] = -p[1]*pow(p[5], 2)*pow(u[2], 2) + 0.94522450735763919; 
data[386] = -p[0]*pow(p[5], 2)*pow(u[2], 2) - 8.928094162434995; 
data[404] = p[0]*(p[5]*u[0] - p[5]*u[2]); 
data[405] = -p[1]*(p[5]*u[0] - p[5]*u[2]); 
data[406] = p[0]*(-p[5]*u[0] + p[5]*u[1]); 
data[407] = -p[1]*(-p[5]*u[0] + p[5]*u[1]); 
data[408] = p[0]*(-p[5]*u[1] + p[5]*u[2]); 
data[409] = -p[1]*(-p[5]*u[1] + p[5]*u[2]); 
data[410] = -p[0]*pow(p[5], 2)*pow(u[0], 2) - 8.9280941624349932; 
data[411] = p[1]*pow(p[5], 2)*pow(u[0], 2) - 0.94522450735763774; 
data[412] = -p[0]*pow(p[5], 2)*pow(u[1], 2) - 7.4244807333189868; 
data[413] = p[1]*pow(p[5], 2)*pow(u[1], 2) - 3.4071408952969091; 
data[414] = -p[0]*pow(p[5], 2)*pow(u[2], 2) - 8.9280941624349932; 
data[415] = p[1]*pow(p[5], 2)*pow(u[2], 2) - 0.94522450735764263; 
data[416] = p[6] + 25.852762655183412 + (p[0]*p[4]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + 1)/p[4]; 
data[417] = -p[1]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) - p[7] + 8.7735859299284922; 
data[435] = p[1]*(p[5]*u[0] - p[5]*u[2]); 
data[436] = p[0]*(p[5]*u[0] - p[5]*u[2]); 
data[437] = p[1]*(-p[5]*u[0] + p[5]*u[1]); 
data[438] = p[0]*(-p[5]*u[0] + p[5]*u[1]); 
data[439] = p[1]*(-p[5]*u[1] + p[5]*u[2]); 
data[440] = p[0]*(-p[5]*u[1] + p[5]*u[2]); 
data[441] = -p[1]*pow(p[5], 2)*pow(u[0], 2) + 0.94522450735763774; 
data[442] = -p[0]*pow(p[5], 2)*pow(u[0], 2) - 8.9280941624349932; 
data[443] = -p[1]*pow(p[5], 2)*pow(u[1], 2) + 3.4071408952969091; 
data[444] = -p[0]*pow(p[5], 2)*pow(u[1], 2) - 7.4244807333189868; 
data[445] = -p[1]*pow(p[5], 2)*pow(u[2], 2) + 0.94522450735764263; 
data[446] = -p[0]*pow(p[5], 2)*pow(u[2], 2) - 8.9280941624349932; 
data[447] = p[1]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + p[7] - 8.7735859299284922; 
data[448] = p[6] + 25.852762655183412 + (p[0]*p[4]*(pow(p[5], 2)*pow(u[0], 2) + pow(p[5], 2)*pow(u[1], 2) + pow(p[5], 2)*pow(u[2], 2)) + 1)/p[4]; 
data[736] = -p[9]; 
data[739] = 1.0*p[8]; 
data[768] = -p[9]; 
data[771] = 1.0*p[8]; 
data[800] = -p[9]; 
data[803] = 1.0*p[8]; 
data[829] = -1.0*p[8]; 
data[832] = -1.0*p[9]; 
data[861] = -1.0*p[8]; 
data[864] = -1.0*p[9]; 
data[893] = -1.0*p[8]; 
data[896] = -1.0*p[9]; 
data[930] = p[11]; 
data[959] = -p[10]; 

}

void de_jac_run_xy_eval(double *data,double *x,double *y,double *u,double *p,double Dt){


}

void de_jac_run_num_eval(double *data,double *x,double *y,double *u,double *p,double Dt){

data[29] = -1; 
data[54] = -1; 
data[88] = -1; 
data[117] = -1; 
data[151] = -1; 
data[180] = -1; 
data[214] = -1; 
data[226] = -8.9280941624349968; 
data[227] = -0.9452245073576433; 
data[228] = -7.4244807333189922; 
data[229] = -3.4071408952969118; 
data[232] = -25.852762655183415; 
data[233] = -8.7735859299284957; 
data[234] = 8.9280941624349968; 
data[235] = 0.9452245073576433; 
data[236] = 7.4244807333189922; 
data[237] = 3.4071408952969118; 
data[238] = 8.9280941624349932; 
data[239] = 0.94522450735763719; 
data[257] = 0.9452245073576433; 
data[258] = -8.9280941624349968; 
data[259] = 3.4071408952969118; 
data[260] = -7.4244807333189922; 
data[263] = 8.7735859299284957; 
data[264] = -25.852762655183415; 
data[265] = -0.9452245073576433; 
data[266] = 8.9280941624349968; 
data[267] = -3.4071408952969118; 
data[268] = 7.4244807333189922; 
data[269] = -0.94522450735763719; 
data[270] = 8.9280941624349932; 
data[286] = -8.9280941624349914; 
data[287] = -0.94522450735763885; 
data[290] = -8.9280941624349897; 
data[291] = -0.9452245073576423; 
data[294] = 8.9280941624349914; 
data[295] = 0.94522450735763885; 
data[296] = -25.852762655183412; 
data[297] = -8.7735859299284975; 
data[298] = 8.9280941624349897; 
data[299] = 0.9452245073576423; 
data[300] = 7.4244807333189877; 
data[301] = 3.4071408952969136; 
data[317] = 0.94522450735763885; 
data[318] = -8.9280941624349914; 
data[321] = 0.9452245073576423; 
data[322] = -8.9280941624349897; 
data[325] = -0.94522450735763885; 
data[326] = 8.9280941624349914; 
data[327] = 8.7735859299284975; 
data[328] = -25.852762655183412; 
data[329] = -0.9452245073576423; 
data[330] = 8.9280941624349897; 
data[331] = -3.4071408952969136; 
data[332] = 7.4244807333189877; 
data[348] = -7.4244807333189904; 
data[349] = -3.4071408952969162; 
data[350] = -8.9280941624349932; 
data[351] = -0.94522450735764241; 
data[356] = 7.4244807333189904; 
data[357] = 3.4071408952969162; 
data[358] = 8.9280941624349932; 
data[359] = 0.94522450735764241; 
data[360] = -25.852762655183412; 
data[361] = -8.7735859299285011; 
data[362] = 8.928094162434995; 
data[363] = 0.94522450735763919; 
data[379] = 3.4071408952969162; 
data[380] = -7.4244807333189904; 
data[381] = 0.94522450735764241; 
data[382] = -8.9280941624349932; 
data[387] = -3.4071408952969162; 
data[388] = 7.4244807333189904; 
data[389] = -0.94522450735764241; 
data[390] = 8.9280941624349932; 
data[391] = 8.7735859299285011; 
data[392] = -25.852762655183412; 
data[393] = -0.94522450735763919; 
data[394] = 8.928094162434995; 
data[418] = 8.9280941624349932; 
data[419] = 0.94522450735763774; 
data[420] = 7.4244807333189868; 
data[421] = 3.4071408952969091; 
data[422] = 8.9280941624349932; 
data[423] = 0.94522450735764263; 
data[424] = -25.852762655183412; 
data[425] = -8.7735859299284922; 
data[449] = -0.94522450735763774; 
data[450] = 8.9280941624349932; 
data[451] = -3.4071408952969091; 
data[452] = 7.4244807333189868; 
data[453] = -0.94522450735764263; 
data[454] = 8.9280941624349932; 
data[455] = 8.7735859299284922; 
data[456] = -25.852762655183412; 
data[472] = -25.852762655183415; 
data[473] = -8.7735859299284957; 
data[474] = 8.9280941624349968; 
data[475] = 0.9452245073576433; 
data[476] = 7.4244807333189922; 
data[477] = 3.4071408952969118; 
data[478] = 8.9280941624349932; 
data[479] = 0.94522450735763719; 
data[480] = 25.852762655183415; 
data[481] = 8.7735859299284957; 
data[482] = -8.9280941624349968; 
data[483] = -0.9452245073576433; 
data[484] = -7.4244807333189922; 
data[485] = -3.4071408952969118; 
data[486] = -8.9280941624349932; 
data[487] = -0.94522450735763719; 
data[503] = 8.7735859299284957; 
data[504] = -25.852762655183415; 
data[505] = -0.9452245073576433; 
data[506] = 8.9280941624349968; 
data[507] = -3.4071408952969118; 
data[508] = 7.4244807333189922; 
data[509] = -0.94522450735763719; 
data[510] = 8.9280941624349932; 
data[511] = -8.7735859299284957; 
data[512] = 25.852762655183415; 
data[513] = 0.9452245073576433; 
data[514] = -8.9280941624349968; 
data[515] = 3.4071408952969118; 
data[516] = -7.4244807333189922; 
data[517] = 0.94522450735763719; 
data[518] = -8.9280941624349932; 
data[534] = 8.9280941624349914; 
data[535] = 0.94522450735763885; 
data[536] = -25.852762655183412; 
data[537] = -8.7735859299284975; 
data[538] = 8.9280941624349897; 
data[539] = 0.9452245073576423; 
data[540] = 7.4244807333189877; 
data[541] = 3.4071408952969136; 
data[542] = -8.9280941624349914; 
data[543] = -0.94522450735763885; 
data[544] = 25.852762655183412; 
data[545] = 8.7735859299284975; 
data[546] = -8.9280941624349897; 
data[547] = -0.9452245073576423; 
data[548] = -7.4244807333189877; 
data[549] = -3.4071408952969136; 
data[565] = -0.94522450735763885; 
data[566] = 8.9280941624349914; 
data[567] = 8.7735859299284975; 
data[568] = -25.852762655183412; 
data[569] = -0.9452245073576423; 
data[570] = 8.9280941624349897; 
data[571] = -3.4071408952969136; 
data[572] = 7.4244807333189877; 
data[573] = 0.94522450735763885; 
data[574] = -8.9280941624349914; 
data[575] = -8.7735859299284975; 
data[576] = 25.852762655183412; 
data[577] = 0.9452245073576423; 
data[578] = -8.9280941624349897; 
data[579] = 3.4071408952969136; 
data[580] = -7.4244807333189877; 
data[596] = 7.4244807333189904; 
data[597] = 3.4071408952969162; 
data[598] = 8.9280941624349932; 
data[599] = 0.94522450735764241; 
data[600] = -25.852762655183412; 
data[601] = -8.7735859299285011; 
data[602] = 8.928094162434995; 
data[603] = 0.94522450735763919; 
data[604] = -7.4244807333189904; 
data[605] = -3.4071408952969162; 
data[606] = -8.9280941624349932; 
data[607] = -0.94522450735764241; 
data[608] = 25.852762655183412; 
data[609] = 8.7735859299285011; 
data[610] = -8.928094162434995; 
data[611] = -0.94522450735763919; 
data[627] = -3.4071408952969162; 
data[628] = 7.4244807333189904; 
data[629] = -0.94522450735764241; 
data[630] = 8.9280941624349932; 
data[631] = 8.7735859299285011; 
data[632] = -25.852762655183412; 
data[633] = -0.94522450735763919; 
data[634] = 8.928094162434995; 
data[635] = 3.4071408952969162; 
data[636] = -7.4244807333189904; 
data[637] = 0.94522450735764241; 
data[638] = -8.9280941624349932; 
data[639] = -8.7735859299285011; 
data[640] = 25.852762655183412; 
data[641] = 0.94522450735763919; 
data[642] = -8.928094162434995; 
data[658] = 8.9280941624349932; 
data[659] = 0.94522450735763774; 
data[660] = 7.4244807333189868; 
data[661] = 3.4071408952969091; 
data[662] = 8.9280941624349932; 
data[663] = 0.94522450735764263; 
data[664] = -25.852762655183412; 
data[665] = -8.7735859299284922; 
data[666] = -8.9280941624349932; 
data[667] = -0.94522450735763774; 
data[668] = -7.4244807333189868; 
data[669] = -3.4071408952969091; 
data[670] = -8.9280941624349932; 
data[671] = -0.94522450735764263; 
data[672] = 25.852762655183412; 
data[673] = 8.7735859299284922; 
data[689] = -0.94522450735763774; 
data[690] = 8.9280941624349932; 
data[691] = -3.4071408952969091; 
data[692] = 7.4244807333189868; 
data[693] = -0.94522450735764263; 
data[694] = 8.9280941624349932; 
data[695] = 8.7735859299284922; 
data[696] = -25.852762655183412; 
data[697] = 0.94522450735763774; 
data[698] = -8.9280941624349932; 
data[699] = 3.4071408952969091; 
data[700] = -7.4244807333189868; 
data[701] = 0.94522450735764263; 
data[702] = -8.9280941624349932; 
data[703] = -8.7735859299284922; 
data[704] = 25.852762655183412; 
data[714] = -1; 
data[747] = -1; 
data[780] = -1; 
data[808] = -1.0; 
data[841] = -1.0; 
data[874] = -1.0; 
data[928] = -1; 
data[960] = -1; 

}



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 8), // void()(double *, double *, double *, double *, double *, double)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_de_jac_run_num_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_num_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_num_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_num_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_num_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_num_eval _cffi_d_de_jac_run_num_eval
#endif

static void _cffi_d_de_jac_run_up_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_up_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_up_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_up_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_up_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_up_eval _cffi_d_de_jac_run_up_eval
#endif

static void _cffi_d_de_jac_run_xy_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  de_jac_run_xy_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_de_jac_run_xy_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "de_jac_run_xy_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { de_jac_run_xy_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_de_jac_run_xy_eval _cffi_d_de_jac_run_xy_eval
#endif

static void _cffi_d_f_run_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  f_run_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_f_run_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "f_run_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { f_run_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_f_run_eval _cffi_d_f_run_eval
#endif

static void _cffi_d_g_run_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  g_run_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_g_run_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "g_run_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { g_run_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_g_run_eval _cffi_d_g_run_eval
#endif

static void _cffi_d_h_eval(double * x0, double * x1, double * x2, double * x3, double * x4, double x5)
{
  h_eval(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_h_eval(PyObject *self, PyObject *args)
{
  double * x0;
  double * x1;
  double * x2;
  double * x3;
  double * x4;
  double x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "h_eval", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x5 = (double)_cffi_to_c_double(arg5);
  if (x5 == (double)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { h_eval(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_h_eval _cffi_d_h_eval
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "de_jac_run_num_eval", (void *)_cffi_f_de_jac_run_num_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_num_eval },
  { "de_jac_run_up_eval", (void *)_cffi_f_de_jac_run_up_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_up_eval },
  { "de_jac_run_xy_eval", (void *)_cffi_f_de_jac_run_xy_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_de_jac_run_xy_eval },
  { "f_run_eval", (void *)_cffi_f_f_run_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_f_run_eval },
  { "g_run_eval", (void *)_cffi_f_g_run_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_g_run_eval },
  { "h_eval", (void *)_cffi_f_h_eval, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_h_eval },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  6,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  9,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_cigre_eu_lv_ind_run_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_cigre_eu_lv_ind_run_cffi(void) { return NULL; }
#  else
     initcigre_eu_lv_ind_run_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_cigre_eu_lv_ind_run_cffi(void)
{
  return _cffi_init("cigre_eu_lv_ind_run_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initcigre_eu_lv_ind_run_cffi(void)
{
  _cffi_init("cigre_eu_lv_ind_run_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
