#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "daesolver.h"

// ==============================================================================
// 1. CONDITIONAL INCLUDES & EXTERN VARIABLES FOR SPARSE MODES
// ==============================================================================
#if defined(USE_SPARSE) || defined(USE_PARDISO) || defined(USE_ACCELERATE)
    // Two separate sparsity patterns: one for ini(), one for run().
    // Written by the Python code generator into the autogenerated C file.
    extern int Ai_ini[];
    extern int Ai_trap[];
    extern const int NNZ_ini;
    extern const int NNZ_trap;
  #ifdef USE_ACCELERATE
    extern long Ap_ini[];
    extern long Ap_trap[];
  #else
    extern int Ap_ini[];
    extern int Ap_trap[];
  #endif
#endif

#ifdef USE_SPARSE
    #include <klu.h>
#endif

#ifdef USE_PARDISO
    void pardiso(void *pt[], int *maxfct, int *mnum, int *mtype, int *phase,
                 int *n, double *a, int *ia, int *ja, int *perm, int *nrhs,
                 int iparm[], int *msglvl, double *b, double *x, int *error);
#endif

#ifdef USE_ACCELERATE
    #include <Accelerate/Accelerate.h>
#endif


// ==============================================================================
// 2. DENSE SOLVER (Fallback / Baseline)
// ==============================================================================
#if !defined(USE_SPARSE) && !defined(USE_PARDISO) && !defined(USE_ACCELERATE)
int solve_dense(double *A, int N, int *pivots, double *b, double *x, int flag) {
    if (flag == 0) {
        for (int i = 0; i < N; i++) pivots[i] = i;
        for (int i = 0; i < N; i++) {
            double max_el = fabs(A[i * N + i]);
            int max_row = i;
            for (int k = i + 1; k < N; k++) {
                if (fabs(A[k * N + i]) > max_el) {
                    max_el = fabs(A[k * N + i]);
                    max_row = k;
                }
            }
            if (max_row != i) {
                int tmp_piv = pivots[i];
                pivots[i] = pivots[max_row];
                pivots[max_row] = tmp_piv;
                for (int k = 0; k < N; k++) {
                    double tmp_val = A[i * N + k];
                    A[i * N + k] = A[max_row * N + k];
                    A[max_row * N + k] = tmp_val;
                }
            }
            if (fabs(A[i * N + i]) < 1e-12) return -1;
            for (int k = i + 1; k < N; k++) {
                A[k * N + i] /= A[i * N + i];
                for (int j = i + 1; j < N; j++) {
                    A[k * N + j] -= A[k * N + i] * A[i * N + j];
                }
            }
        }
    } else if (flag == 1) {
        for (int i = 0; i < N; i++) x[i] = b[pivots[i]];
        for (int i = 0; i < N; i++) {
            for (int k = 0; k < i; k++) {
                x[i] -= A[i * N + k] * x[k];
            }
        }
        for (int i = N - 1; i >= 0; i--) {
            for (int k = i + 1; k < N; k++) {
                x[i] -= A[i * N + k] * x[k];
            }
            x[i] /= A[i * N + i];
        }
    }
    return 0;
}
#endif


// ==============================================================================
// 3. PARDISO HELPER
// ==============================================================================
#ifdef USE_PARDISO
static void pardiso_default_iparm(int iparm[]) {
    for (int i = 0; i < 64; i++) iparm[i] = 0;
    iparm[0]  = 1;
    iparm[1]  = 2;
    iparm[3]  = 0;
    iparm[4]  = 0;
    iparm[5]  = 0;
    iparm[7]  = 2;
    iparm[9]  = 13;
    iparm[10] = 1;
    iparm[12] = 1;
    iparm[17] = -1;
    iparm[18] = -1;
    iparm[34] = 0;
    /* The sparsity pattern is in CSC form (Ap = column pointers, Ai = row
     * indices).  PARDISO expects CSR (Ap = row pointers, Ai = column
     * indices).  Feeding CSC arrays to PARDISO as if they were CSR is
     * equivalent to factorising the transpose A^T.  Setting iparm[11] = 2
     * tells PARDISO to solve A^T x = b, which recovers the correct
     * forward solution A x = b.  Without this the Newton loop diverges. */
    iparm[11] = 2;
}
#endif


// ==============================================================================
// 4. ACCELERATE HELPERS (one per pattern)
// ==============================================================================
#ifdef USE_ACCELERATE
static SparseMatrix_Double accel_make_matrix_ini(int N, double *values) {
    SparseAttributes_t attr = { .transpose = false, .triangle = SparseUpperTriangle,
                                .kind = SparseOrdinary, ._reserved = 0, ._allocatedBySparse = false };
    SparseMatrixStructure structure = { .rowCount = N, .columnCount = N,
        .columnStarts = Ap_ini, .rowIndices = Ai_ini, .attributes = attr, .blockSize = 1 };
    SparseMatrix_Double A = { .structure = structure, .data = values };
    return A;
}

static SparseMatrix_Double accel_make_matrix_trap(int N, double *values) {
    SparseAttributes_t attr = { .transpose = false, .triangle = SparseUpperTriangle,
                                .kind = SparseOrdinary, ._reserved = 0, ._allocatedBySparse = false };
    SparseMatrixStructure structure = { .rowCount = N, .columnCount = N,
        .columnStarts = Ap_trap, .rowIndices = Ai_trap, .attributes = attr, .blockSize = 1 };
    SparseMatrix_Double A = { .structure = structure, .data = values };
    return A;
}
#endif


// ==============================================================================
// 5. INITIALIZATION SOLVER (uses Ap_ini / Ai_ini)
// ==============================================================================
int ini(double *jac_ini, int *pivots, double *x, double *y, double *xy, double *Dxy,
        double *u, double *p, int N_x, int N_y, int max_it, double itol,
        double *z, double *inidblparams, int *iniintparams, double *f, double *g, double *fg) {

    int i, it;
    double norma;
    int N = N_x + N_y;
    double Dt = 0.0;

    // --- DIAGNOSTIC MODE (iniintparams[4] == 1) ---
    // Populate fg and jac_ini from a single evaluation at (x, y) without
    // running Newton. Dense-only: the sparse backends pack values into NNZ
    // arrays which the diagnostic inspector reconstructs via Ap/Ai.
    if (iniintparams[4] == 1) {
        f_ini_eval(f, x, y, u, p, Dt);
        g_ini_eval(g, x, y, u, p, Dt);
        for (i = 0; i < N_x; i++) fg[i] = -f[i];
        for (i = 0; i < N_y; i++) fg[i + N_x] = -g[i];
#if !defined(USE_SPARSE) && !defined(USE_PARDISO) && !defined(USE_ACCELERATE)
        for (int k = 0; k < N * N; k++) jac_ini[k] = 0.0;
#endif
        jac_ini_eval(jac_ini, x, y, u, p, Dt);
        return 0;
    }

#ifdef USE_SPARSE
    klu_common Common;
    klu_symbolic *Symbolic = NULL;
    klu_numeric *Numeric = NULL;
    klu_defaults(&Common);
    Symbolic = klu_analyze(N, Ap_ini, Ai_ini, &Common);
#endif

#ifdef USE_PARDISO
    void *pt[64];
    int iparm[64];
    int maxfct = 1, mnum = 1, mtype = 11;
    int nrhs = 1, msglvl = 0, error = 0;
    int phase;
    int *perm = (int*)malloc(N * sizeof(int));
    double *pardiso_x = (double*)malloc(N * sizeof(double));
    for (i = 0; i < 64; i++) pt[i] = NULL;
    pardiso_default_iparm(iparm);
    phase = 11;
    pardiso(pt, &maxfct, &mnum, &mtype, &phase,
            &N, jac_ini, Ap_ini, Ai_ini, perm, &nrhs,
            iparm, &msglvl, fg, pardiso_x, &error);
    if (error != 0) { free(perm); free(pardiso_x); return -1; }
#endif

#ifdef USE_ACCELERATE
    SparseMatrix_Double A_sparse = accel_make_matrix_ini(N, jac_ini);
    SparseOpaqueFactorization_Double Factored = {0};
    int accel_factored = 0;
#endif

    for (it = 0; it < max_it; it++) {
        f_ini_eval(f, x, y, u, p, Dt);
        g_ini_eval(g, x, y, u, p, Dt);

        for (i = 0; i < N_x; i++) fg[i] = -f[i];
        for (i = 0; i < N_y; i++) fg[i + N_x] = -g[i];

        if (iniintparams[0] == 0 || (iniintparams[0] == 1 && it == 0)) {
#ifdef USE_SPARSE
            jac_ini_eval(jac_ini, x, y, u, p, Dt); 
            if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
            Numeric = klu_factor(Ap_ini, Ai_ini, jac_ini, Symbolic, &Common);
            if (Common.status != KLU_OK) return -1;
#elif defined(USE_PARDISO)
            jac_ini_eval(jac_ini, x, y, u, p, Dt);
            phase = 22;
            pardiso(pt, &maxfct, &mnum, &mtype, &phase,
                    &N, jac_ini, Ap_ini, Ai_ini, perm, &nrhs,
                    iparm, &msglvl, fg, pardiso_x, &error);
            if (error != 0) { 
                phase = -1;
                pardiso(pt, &maxfct, &mnum, &mtype, &phase,
                        &N, jac_ini, Ap_ini, Ai_ini, perm, &nrhs,
                        iparm, &msglvl, fg, pardiso_x, &error);
                free(perm); free(pardiso_x); return -1; 
            }
#elif defined(USE_ACCELERATE)
            jac_ini_eval(jac_ini, x, y, u, p, Dt);
            A_sparse.data = jac_ini;
            if (!accel_factored) {
                Factored = SparseFactor(SparseFactorizationQR, A_sparse);
                accel_factored = 1;
            } else {
                SparseRefactor(A_sparse, &Factored);
            }
            if (Factored.status != SparseStatusOK) {
                if (accel_factored) SparseCleanup(Factored);
                return -1;
            }
#else
            for (int k = 0; k < N * N; k++) jac_ini[k] = 0.0;
            jac_ini_eval(jac_ini, x, y, u, p, Dt);
            if (solve_dense(jac_ini, N, pivots, fg, Dxy, 0) != 0) return -1;
#endif
            iniintparams[3] += 1; 
        }

#ifdef USE_SPARSE
        for (i = 0; i < N; i++) Dxy[i] = fg[i];
        klu_solve(Symbolic, Numeric, N, 1, Dxy, &Common);
#elif defined(USE_PARDISO)
        phase = 33;
        pardiso(pt, &maxfct, &mnum, &mtype, &phase,
                &N, jac_ini, Ap_ini, Ai_ini, perm, &nrhs,
                iparm, &msglvl, fg, Dxy, &error);
#elif defined(USE_ACCELERATE)
        {
            DenseVector_Double rhs_vec = { .count = N, .data = fg  };
            DenseVector_Double sol_vec = { .count = N, .data = Dxy };
            SparseSolve(Factored, rhs_vec, sol_vec);
        }
#else
        solve_dense(jac_ini, N, pivots, fg, Dxy, 1);
#endif

        for (i = 0; i < N; i++) xy[i] += Dxy[i];
        for (i = 0; i < N_x; i++) x[i] = xy[i];
        for (i = 0; i < N_y; i++) y[i] = xy[i + N_x];

        norma = 0.0;
        for (i = 0; i < N; i++) norma += Dxy[i] * Dxy[i];
        if (norma < itol) break;
    }

#ifdef USE_SPARSE
    klu_free_symbolic(&Symbolic, &Common);
    if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
#endif
#ifdef USE_PARDISO
    phase = -1;
    pardiso(pt, &maxfct, &mnum, &mtype, &phase,
            &N, jac_ini, Ap_ini, Ai_ini, perm, &nrhs,
            iparm, &msglvl, fg, Dxy, &error);
    free(perm); free(pardiso_x);
#endif
#ifdef USE_ACCELERATE
    if (accel_factored) SparseCleanup(Factored);
#endif

    iniintparams[2] = it;
    if (iniintparams[1] == 0) h_eval(z, x, y, u, p, Dt);
    return 0;
}


// ==============================================================================
// 6. TIME DOMAIN SOLVER (uses Ap_trap / Ai_trap)
// ==============================================================================
int run(double t, double t_end, double *jac_trap, int *pivots, double *x, double *y, double *xy, 
        double *u, double *p, int N_x, int N_y, int max_it, double itol, 
        int *its, double Dt, double *z, double *dblparams, int *intparams, double *Time, 
        double *X, double *Y, double *Z, int N_z, int N_store, double *f, double *g, double *fg) {
    
    int i, j, it = 0;
    double norma;
    int N = N_x + N_y;
    int decimation = (intparams[4] > 0) ? intparams[4] : 1;

    double* x_0 = (double*)malloc(N_x * sizeof(double));
    double* f_0 = (double*)malloc(N_x * sizeof(double));
    double* Dxy = (double*)malloc(N * sizeof(double));

#ifdef USE_SPARSE
    klu_common Common;
    klu_symbolic *Symbolic = NULL;
    klu_numeric *Numeric = NULL;
    klu_defaults(&Common);
    Symbolic = klu_analyze(N, Ap_trap, Ai_trap, &Common);
#endif

#ifdef USE_PARDISO
    void *pt[64];
    int iparm[64];
    int maxfct = 1, mnum = 1, mtype = 11;
    int nrhs = 1, msglvl = 0, error = 0;
    int phase;
    int *perm = (int*)malloc(N * sizeof(int));
    double *pardiso_x = (double*)malloc(N * sizeof(double));
    for (i = 0; i < 64; i++) pt[i] = NULL;
    pardiso_default_iparm(iparm);
    phase = 11;
    pardiso(pt, &maxfct, &mnum, &mtype, &phase,
            &N, jac_trap, Ap_trap, Ai_trap, perm, &nrhs,
            iparm, &msglvl, fg, pardiso_x, &error);
    if (error != 0) { 
        free(x_0); free(f_0); free(Dxy); free(perm); free(pardiso_x); 
        return -1; 
    }
#endif

#ifdef USE_ACCELERATE
    SparseMatrix_Double A_sparse = accel_make_matrix_trap(N, jac_trap);
    SparseOpaqueFactorization_Double Factored = {0};
    int accel_factored = 0;
#endif

    if (intparams[1] == 0 && intparams[7] == 0) {
        h_eval(z, x, y, u, p, Dt);
        Time[its[0]] = t;
        for (i = 0; i < N_x; i++) X[its[0] * N_x + i] = x[i];
        for (i = 0; i < N_y; i++) Y[its[0] * N_y + i] = y[i];
        for (i = 0; i < N_z; i++) Z[its[0] * N_z + i] = z[i];
        its[0]++;
    }

    while (t < t_end - 1e-9) {    
        t += Dt;
        intparams[7] += 1; 
        
        for (i = 0; i < N_x; i++) { 
            f_0[i] = f[i]; 
            x_0[i] = x[i]; 
        }

        for (it = 0; it < max_it; it++) {
            f_run_eval(f, x, y, u, p, Dt);
            g_run_eval(g, x, y, u, p, Dt);

            for (i = 0; i < N_x; i++) {
                fg[i] = -(x[i] - x_0[i] - Dt * (dblparams[0] * f[i] + (1.0 - dblparams[0]) * f_0[i]));
            }
            for (i = 0; i < N_y; i++) {
                fg[i + N_x] = -g[i]; 
            }

            if (intparams[0] == 0 || (intparams[0] == 1 && it == 0)) { 
#ifdef USE_SPARSE
                jac_trap_eval(jac_trap, x, y, u, p, Dt);
                if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
                Numeric = klu_factor(Ap_trap, Ai_trap, jac_trap, Symbolic, &Common);
                if (Common.status != KLU_OK) { free(x_0); free(f_0); free(Dxy); return -1; }
#elif defined(USE_PARDISO)
                jac_trap_eval(jac_trap, x, y, u, p, Dt);
                phase = 22;
                pardiso(pt, &maxfct, &mnum, &mtype, &phase,
                        &N, jac_trap, Ap_trap, Ai_trap, perm, &nrhs,
                        iparm, &msglvl, fg, pardiso_x, &error);
                if (error != 0) { 
                    phase = -1;
                    pardiso(pt, &maxfct, &mnum, &mtype, &phase,
                            &N, jac_trap, Ap_trap, Ai_trap, perm, &nrhs,
                            iparm, &msglvl, fg, pardiso_x, &error);
                    free(x_0); free(f_0); free(Dxy); free(perm); free(pardiso_x); 
                    return -1; 
                }
#elif defined(USE_ACCELERATE)
                jac_trap_eval(jac_trap, x, y, u, p, Dt);
                A_sparse.data = jac_trap;
                if (!accel_factored) {
                    Factored = SparseFactor(SparseFactorizationQR, A_sparse);
                    accel_factored = 1;
                } else {
                    SparseRefactor(A_sparse, &Factored);
                }
                if (Factored.status != SparseStatusOK) {
                    if (accel_factored) SparseCleanup(Factored);
                    free(x_0); free(f_0); free(Dxy);
                    return -1;
                }
#else
                for (int k = 0; k < N * N; k++) jac_trap[k] = 0.0;
                jac_trap_eval(jac_trap, x, y, u, p, Dt);
                double k_jac = 1.0;
                if (dblparams[0] != 0.5) {
                    k_jac = dblparams[0] / 0.5;
                    for (i = 0; i < N_x; i++) {
                        for (j = 0; j < N; j++) {
                            int idx = i * N + j;
                            if (i == j) jac_trap[idx] = k_jac * jac_trap[idx] + (1.0 - k_jac);
                            else jac_trap[idx] = k_jac * jac_trap[idx];
                        }
                    }
                }
                if (solve_dense(jac_trap, N, pivots, fg, Dxy, 0) != 0) {
                    free(x_0); free(f_0); free(Dxy); return -1;
                }
#endif
                intparams[3] += 1;
            }
            
#ifdef USE_SPARSE
            for (i = 0; i < N; i++) Dxy[i] = fg[i];
            klu_solve(Symbolic, Numeric, N, 1, Dxy, &Common);
#elif defined(USE_PARDISO)
            phase = 33;
            pardiso(pt, &maxfct, &mnum, &mtype, &phase,
                    &N, jac_trap, Ap_trap, Ai_trap, perm, &nrhs,
                    iparm, &msglvl, fg, Dxy, &error);
#elif defined(USE_ACCELERATE)
            {
                DenseVector_Double rhs_vec = { .count = N, .data = fg  };
                DenseVector_Double sol_vec = { .count = N, .data = Dxy };
                SparseSolve(Factored, rhs_vec, sol_vec);
            }
#else
            solve_dense(jac_trap, N, pivots, fg, Dxy, 1);
#endif

            for (i = 0; i < N; i++) xy[i] += Dxy[i];         
            for (i = 0; i < N_x; i++) x[i] = xy[i]; 
            for (i = 0; i < N_y; i++) y[i] = xy[i + N_x]; 

            norma = 0.0;
            for (i = 0; i < N; i++) norma += Dxy[i] * Dxy[i];
            if (norma < itol) break;
        }

        if (intparams[1] == 0 && its[0] < N_store && (intparams[7] % decimation == 0)) {
            h_eval(z, x, y, u, p, Dt);
            Time[its[0]] = t;
            for (i = 0; i < N_x; i++) X[its[0] * N_x + i] = x[i];
            for (i = 0; i < N_y; i++) Y[its[0] * N_y + i] = y[i];
            for (i = 0; i < N_z; i++) Z[its[0] * N_z + i] = z[i];
            its[0]++;
        }
    }    

#ifdef USE_SPARSE
    klu_free_symbolic(&Symbolic, &Common);
    if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
#endif
#ifdef USE_PARDISO
    phase = -1;
    pardiso(pt, &maxfct, &mnum, &mtype, &phase,
            &N, jac_trap, Ap_trap, Ai_trap, perm, &nrhs,
            iparm, &msglvl, fg, Dxy, &error);
    free(perm); free(pardiso_x);
#endif
#ifdef USE_ACCELERATE
    if (accel_factored) SparseCleanup(Factored);
#endif

    free(x_0); 
    free(f_0); 
    free(Dxy);
    
    intparams[2] = it; 
    return 0;
}
