#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "daesolver.h"

// ==============================================================================
// 1. CONDITIONAL INCLUDES & EXTERN VARIABLES FOR SPARSE MODE
// ==============================================================================
#ifdef USE_SPARSE
    #include <klu.h>
    // These arrays are written directly into the autogenerated C file by Python
    extern int Ap[];
    extern int Ai[];
    extern const int NNZ;
#endif

// ==============================================================================
// 2. DENSE SOLVER (Fallback / Baseline)
// ==============================================================================
#ifndef USE_SPARSE
/* PORTABLE DENSE LINEAR SOLVER: LU Decomposition with Partial Pivoting
 * flag = 0: Factorize matrix A in-place into LU, populate pivots
 * flag = 1: Solve Ax = b using the existing in-place LU factorization
 */
int solve_dense(double *A, int N, int *pivots, double *b, double *x, int flag) {
    if (flag == 0) {
        for (int i = 0; i < N; i++) pivots[i] = i;
        for (int i = 0; i < N; i++) {
            double max_el = fabs(A[i * N + i]);
            int max_row = i;
            for (int k = i + 1; k < N; k++) {
                if (fabs(A[k * N + i]) > max_el) {
                    max_el = fabs(A[k * N + i]);
                    max_row = k;
                }
            }
            if (max_row != i) {
                int tmp_piv = pivots[i];
                pivots[i] = pivots[max_row];
                pivots[max_row] = tmp_piv;
                for (int k = 0; k < N; k++) {
                    double tmp_val = A[i * N + k];
                    A[i * N + k] = A[max_row * N + k];
                    A[max_row * N + k] = tmp_val;
                }
            }
            double pivot_val = A[i * N + i];
            if (isnan(pivot_val) || isinf(pivot_val) || fabs(pivot_val) < 1e-12) return -1;
            for (int k = i + 1; k < N; k++) {
                A[k * N + i] /= A[i * N + i];
                for (int j = i + 1; j < N; j++) {
                    A[k * N + j] -= A[k * N + i] * A[i * N + j];
                }
            }
        }
    } else if (flag == 1) {
        for (int i = 0; i < N; i++) x[i] = b[pivots[i]];
        for (int i = 0; i < N; i++) {
            for (int k = 0; k < i; k++) {
                x[i] -= A[i * N + k] * x[k];
            }
        }
        for (int i = N - 1; i >= 0; i--) {
            for (int k = i + 1; k < N; k++) {
                x[i] -= A[i * N + k] * x[k];
            }
            x[i] /= A[i * N + i];
        }
    }
    return 0;
}
#endif


// ==============================================================================
// 3. INITIALIZATION SOLVER (Steady-State / Newton-Raphson)
// ==============================================================================
int ini(double *jac_ini, int *pivots, double *x, double *y, double *xy, double *Dxy, 
        double *u, double *p, int N_x, int N_y, int max_it, double itol, 
        double *z, double *inidblparams, int *iniintparams, double *f, double *g, double *fg) {
    
    int i, it;
    double norma;
    int N = N_x + N_y;
    double Dt = 0.0; // Dt is 0 for initialization

#ifdef USE_SPARSE
    klu_common Common;
    klu_symbolic *Symbolic = NULL;
    klu_numeric *Numeric = NULL;
    klu_defaults(&Common);
    // Symbolic factorization (Analyze the non-zero pattern once)
    Symbolic = klu_analyze(N, Ap, Ai, &Common);
#endif

    for (it = 0; it < max_it; it++) {
        f_ini_eval(f, x, y, u, p, Dt);
        g_ini_eval(g, x, y, u, p, Dt);

        // Assemble RHS
        for (i = 0; i < N_x; i++) fg[i] = -f[i];
        for (i = 0; i < N_y; i++) fg[i + N_x] = -g[i];

        if (iniintparams[0] == 0 || (iniintparams[0] == 1 && it == 0)) {
#ifdef USE_SPARSE
            // jac_ini points to the packed Ax array
            jac_ini_eval(jac_ini, x, y, u, p, Dt); 
            if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
            Numeric = klu_factor(Ap, Ai, jac_ini, Symbolic, &Common);
            if (Common.status != KLU_OK) {
                klu_free_symbolic(&Symbolic, &Common);
                if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
                return -1;
            }
#else
            // jac_ini points to the N*N dense array
            for (int k = 0; k < N * N; k++) jac_ini[k] = 0.0;
            jac_ini_eval(jac_ini, x, y, u, p, Dt);
            if (solve_dense(jac_ini, N, pivots, fg, Dxy, 0) != 0) return -1;
#endif
            iniintparams[3] += 1; 
        }

#ifdef USE_SPARSE
        // Copy RHS to Dxy workspace to match the dense solver behavior
        for (i = 0; i < N; i++) Dxy[i] = fg[i];
        klu_tsolve(Symbolic, Numeric, N, 1, Dxy, &Common);
#else
        solve_dense(jac_ini, N, pivots, fg, Dxy, 1);
#endif

        // Update states
        for (i = 0; i < N; i++) xy[i] += Dxy[i];
        for (i = 0; i < N_x; i++) x[i] = xy[i];
        for (i = 0; i < N_y; i++) y[i] = xy[i + N_x];

        // Check convergence
        norma = 0.0;
        for (i = 0; i < N; i++) norma += Dxy[i] * Dxy[i];
        if (norma < itol) break;
    }

#ifdef USE_SPARSE
    klu_free_symbolic(&Symbolic, &Common);
    if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
#endif

    iniintparams[2] = it;
    if (iniintparams[1] == 0) h_eval(z, x, y, u, p, Dt);
    return 0;
}


// ==============================================================================
// 4. TIME DOMAIN SOLVER (Implicit Trapezoidal / Backward Euler)
// ==============================================================================
// Notice: double *Dxy is NOT in the arguments anymore to match Python ctypes.
int run(double t, double t_end, double *jac_trap, int *pivots, double *x, double *y, double *xy, 
        double *u, double *p, int N_x, int N_y, int max_it, double itol, 
        int *its, double Dt, double *z, double *dblparams, int *intparams, double *Time, 
        double *X, double *Y, double *Z, int N_z, int N_store, double *f, double *g, double *fg) {
    
    int i, j, it;
    double norma;
    int N = N_x + N_y;
    int decimation = (intparams[4] > 0) ? intparams[4] : 1;

    // --- Dynamic Memory Allocation ---
    double* x_0 = (double*)calloc(N_x, sizeof(double));
    double* f_0 = (double*)calloc(N_x, sizeof(double));
    double* Dxy = (double*)calloc(N, sizeof(double));
    if (!x_0 || !f_0 || !Dxy) {
        if (x_0) free(x_0);
        if (f_0) free(f_0);
        if (Dxy) free(Dxy);
        return -2;
    }

#ifdef USE_SPARSE
    klu_common Common;
    klu_symbolic *Symbolic = NULL;
    klu_numeric *Numeric = NULL;
    klu_defaults(&Common);
    Symbolic = klu_analyze(N, Ap, Ai, &Common);
#endif

    // Initial storage if at t=0
    if (intparams[1] == 0 && intparams[7] == 0) {
        h_eval(z, x, y, u, p, Dt);
        Time[its[0]] = t;
        for (i = 0; i < N_x; i++) X[its[0] * N_x + i] = x[i];
        for (i = 0; i < N_y; i++) Y[its[0] * N_y + i] = y[i];
        for (i = 0; i < N_z; i++) Z[its[0] * N_z + i] = z[i];
        its[0]++;
    }

    // Main Integration Loop
    while (t < t_end - 1e-9) {    
        t += Dt;
        intparams[7] += 1; 
        
        // Save previous step states and derivatives
        for (i = 0; i < N_x; i++) { 
            f_0[i] = f[i]; 
            x_0[i] = x[i]; 
        }

        // Newton-Raphson Loop
        for (it = 0; it < max_it; it++) {
            f_run_eval(f, x, y, u, p, Dt);
            g_run_eval(g, x, y, u, p, Dt);

            // Assemble RHS (Trapezoidal / Euler depending on dblparams[0] which is alpha)
            for (i = 0; i < N_x; i++) {
                fg[i] = -(x[i] - x_0[i] - Dt * (dblparams[0] * f[i] + (1.0 - dblparams[0]) * f_0[i]));
            }
            for (i = 0; i < N_y; i++) {
                fg[i + N_x] = -g[i]; 
            }

            // Update Jacobian
            if (intparams[0] == 0 || (intparams[0] == 1 && it == 0)) { 
#ifdef USE_SPARSE
                jac_trap_eval(jac_trap, x, y, u, p, Dt);
                
                // Note: The 'alpha' integration factor logic is handled purely by 
                // SymPy mapping the parameter 'p[idx]' directly into jac_trap_eval.
                
                if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
                Numeric = klu_factor(Ap, Ai, jac_trap, Symbolic, &Common);
                if (Common.status != KLU_OK) {
                    klu_free_symbolic(&Symbolic, &Common);
                    if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
                    free(x_0); free(f_0); free(Dxy); return -1;
                }
#else
                for (int k = 0; k < N * N; k++) jac_trap[k] = 0.0;
                jac_trap_eval(jac_trap, x, y, u, p, Dt);

                // Dense-specific logic: Apply integration factor (alpha) to the diagonal
                double k_jac = 1.0;
                if (dblparams[0] != 0.5) {
                    k_jac = dblparams[0] / 0.5;
                    for (i = 0; i < N_x; i++) {
                        for (j = 0; j < N; j++) {
                            int idx = i * N + j;
                            if (i == j) jac_trap[idx] = k_jac * jac_trap[idx] + (1.0 - k_jac);
                            else jac_trap[idx] = k_jac * jac_trap[idx];
                        }
                    }
                }
                if (solve_dense(jac_trap, N, pivots, fg, Dxy, 0) != 0) {
                    free(x_0); free(f_0); free(Dxy); return -1;
                }
#endif
                intparams[3] += 1; // Update factorizations counter
            }
            
            // Linear Solve
#ifdef USE_SPARSE
            for (i = 0; i < N; i++) Dxy[i] = fg[i];
            klu_tsolve(Symbolic, Numeric, N, 1, Dxy, &Common);
#else
            solve_dense(jac_trap, N, pivots, fg, Dxy, 1);
#endif

            // Update States
            for (i = 0; i < N; i++) xy[i] += Dxy[i];         
            for (i = 0; i < N_x; i++) x[i] = xy[i]; 
            for (i = 0; i < N_y; i++) y[i] = xy[i + N_x]; 

            // Check Convergence
            norma = 0.0;
            for (i = 0; i < N; i++) norma += Dxy[i] * Dxy[i];
            if (norma < itol) break;
        }

        // DECIMATED STORAGE
        if (intparams[1] == 0 && its[0] < N_store && (intparams[7] % decimation == 0)) {
            h_eval(z, x, y, u, p, Dt);
            Time[its[0]] = t;
            for (i = 0; i < N_x; i++) X[its[0] * N_x + i] = x[i];
            for (i = 0; i < N_y; i++) Y[its[0] * N_y + i] = y[i];
            for (i = 0; i < N_z; i++) Z[its[0] * N_z + i] = z[i];
            its[0]++;
        }
    }    

    // --- Clean up ---
#ifdef USE_SPARSE
    klu_free_symbolic(&Symbolic, &Common);
    if (Numeric != NULL) klu_free_numeric(&Numeric, &Common);
#endif

    free(x_0); 
    free(f_0); 
    free(Dxy); // <-- FREE THE INTERNAL WORKSPACE
    
    intparams[2] = it; 
    return 0;
}